# PATHs
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$HOME/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

[ -f /usr/libexec/java_home ] && export JAVA_HOME=$(/usr/libexec/java_home)

# Create aliases.local if doesn't exist
root=$HOME
touch $root/.aliases.local

# Source files
source $root/.exports     # Various exports
source $root/.aliases     # User-defined aliases
source $root/.aliases.local     # Extra aliases
source $root/.bash_colors # Color codes
source $root/.bash_prompt # Bash prompt
